p8105_hw3_yh3554
================

# Problem 1

Load the data from `p8105.datasets`.

``` r
library(p8105.datasets)
data("instacart")
```

#### Exploring the dataset

``` r
head(instacart %>% 
  group_by(department, aisle, product_name) %>%
  summarize(n = n()) %>%
  mutate(rank = min_rank(desc(n))) %>%
  filter(rank < 4) %>%
  arrange(desc(n)))
```

    ## `summarise()` has grouped output by 'department', 'aisle'. You can override
    ## using the `.groups` argument.

    ## # A tibble: 6 × 5
    ## # Groups:   department, aisle [2]
    ##   department aisle                      product_name               n  rank
    ##   <chr>      <chr>                      <chr>                  <int> <int>
    ## 1 produce    fresh fruits               Banana                 18726     1
    ## 2 produce    fresh fruits               Bag of Organic Bananas 15480     2
    ## 3 produce    fresh fruits               Organic Strawberries   10894     3
    ## 4 produce    packaged vegetables fruits Organic Baby Spinach    9784     1
    ## 5 produce    packaged vegetables fruits Organic Raspberries     5546     2
    ## 6 produce    packaged vegetables fruits Organic Blueberries     4966     3

#### Summary of instacart dataset

The instacart dataset is online grocery data from the Instacart in 2017.
It has 1384617 observations and 15 variables. Each observation from the
dataset is a product from an order. The dataset includes identifier,
product information, order number, order from cart or not, reorder from
past or not, customer identifier, time variables the ordered was placed,
aisle information, and department information.  
The key variables are user identifier, product identifier, product name,
aside, department name, day which ordered in a week, hour which ordered
in a day, day since prior order, and order numbers. There are 131209
customers using the app. The mean hour which ordered in a day is 14, the
earliest hour is 0, the lastest hour is 23. The most popular products
are banana, bag of organic bananas, organic, strawberries, raby spinach,
raspberries, and bluebeeries which are all from produce department.  
For example, Row 1 indicates one customer purchased Bulgarian Yogurt at
10 o’clock on Thursday. This customer had made 3 purchases before this
order. This customer picked the product from yogurt aisle in the dairy
eggs department.

#### Total number of aisles and most popular aisles.

Apply `distinct()` to find the numbers of aisles, and use `count()` to
find the most popular aisles.

``` r
p1_df1 <- instacart %>% 
  select(aisle, department, aisle_id) %>%
  arrange(aisle) %>%
  distinct(aisle, .keep_all = TRUE)

p1_df2 <- instacart %>%
  count(aisle, name = "n_obs") %>%
  arrange(desc(n_obs))
head(p1_df2)
```

    ## # A tibble: 6 × 2
    ##   aisle                          n_obs
    ##   <chr>                          <int>
    ## 1 fresh vegetables              150609
    ## 2 fresh fruits                  150473
    ## 3 packaged vegetables fruits     78493
    ## 4 yogurt                         55240
    ## 5 packaged cheese                41699
    ## 6 water seltzer sparkling water  36617

There are 134 aisles, and the aisles have the most ordered item are
fresh vegetables, fresh fruits, and packaged vegetables fruits which
corresponding to 150609, 150473, and 78493 items.

#### Plot of number of items ordered for each aisles with more than 10,000 items

``` r
p1_df3 <- instacart %>%
  count(aisle, name = "n_items") %>%
  arrange(desc(n_items)) %>%
  filter(n_items >= 10000)

numbers_items_barplot <- p1_df3 %>%
  ggplot(aes(reorder(aisle, n_items), n_items, fill = aisle)) + 
  geom_bar(stat = "identity") + 
  labs(
    x = "aisle",
    y = "number of items",
    title = "Boxplot of number of items in each aisle"
    ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), 
        legend.position = "none")

numbers_items_barplot
```

![](p8105_hw3_yh3554_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

#### Table of three most popular items in “baking ingredients”, “dog food care”, and “packaged vegatables fruits”.

``` r
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle, product_name) %>%
  summarize(n = n()) %>%
  mutate(rank = min_rank(desc(n))) %>%
  filter(rank < 4) %>%
  arrange(aisle, rank) %>%
  knitr::kable(digit = 0, caption = "most popular items in each aisles")
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the
    ## `.groups` argument.

| aisle                      | product_name                                  |    n | rank |
|:---------------------------|:----------------------------------------------|-----:|-----:|
| baking ingredients         | Light Brown Sugar                             |  499 |    1 |
| baking ingredients         | Pure Baking Soda                              |  387 |    2 |
| baking ingredients         | Cane Sugar                                    |  336 |    3 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |   30 |    1 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |   28 |    2 |
| dog food care              | Small Dog Biscuits                            |   26 |    3 |
| packaged vegetables fruits | Organic Baby Spinach                          | 9784 |    1 |
| packaged vegetables fruits | Organic Raspberries                           | 5546 |    2 |
| packaged vegetables fruits | Organic Blueberries                           | 4966 |    3 |

most popular items in each aisles

#### Table of mean hour of the day at Pink Lady Apples and Coffee Ice Cream are ordered in a week

``` r
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  mutate(order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", 
                   "4" = "Thursday", "5" = "Friday", "6" = "Saturday")) %>%
  pivot_wider(names_from = "order_dow", values_from = "mean_hour") %>%
  knitr::kable(digit = 0, digits = 2, caption = "mean hour of given product are ordered in a week")
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the
    ## `.groups` argument.

| product_name     | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
|:-----------------|-------:|-------:|--------:|----------:|---------:|-------:|---------:|
| Coffee Ice Cream |  13.77 |  14.32 |   15.38 |     15.32 |    15.22 |  12.26 |    13.83 |
| Pink Lady Apples |  13.44 |  11.36 |   11.70 |     14.25 |    11.55 |  12.78 |    11.94 |

mean hour of given product are ordered in a week

# Problem 2
